name: travelerapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  flutter_bloc: ^9.0.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  equatable: ^2.0.5
  bloc: ^9.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  geolocator: ^13.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
